// Custom exports that are not generated by openapi-typescript-codegen
// These should be imported separately or re-exported from index.ts

// StockAlert and StockAlertsResponse type aliases (placeholder - these may not exist in generated API)
export type StockAlert = {
  id?: number;
  type?: string;
  severity?: string;
  title?: string;
  message?: string;
  product_id?: number;
  product_name?: string;
  current_stock?: number;
  min_threshold?: number;
  action?: string;
  link?: string;
  unit_id?: number;
  expires_at?: string;
  reserved_by?: string;
  hours_remaining?: number;
  count?: number;
};

export type StockAlertsResponse = {
  alerts: Array<StockAlert>;
  count?: number;
};

// Alert type constants
export const StockAlertType = {
  OUT_OF_STOCK: 'out_of_stock',
  LOW_STOCK: 'low_stock',
  EXPIRING_RESERVATION: 'expiring_reservation',
  PENDING_APPROVAL: 'pending_approval',
} as const;
