// Import User type for UserCompat
import type {
  User,
  InventoryUnit,
  Product,
  Order,
  OrderItem,
  Lead,
  UnitAcquisitionSource,
  ProductAccessory,
  CustomerLogin,
  Admin,
} from '@shwari/api-client';

export * from '@shwari/api-client';
export { OpenAPI } from '@shwari/api-client';
export type { OpenAPIConfig } from '@shwari/api-client';

// Type aliases for backward compatibility
export type InventoryUnitRW = InventoryUnit;
export type ProductTemplate = Product;
export type OrderResponse = Order;
export type OrderItemResponse = OrderItem;
export type LeadAdmin = Lead;
export type AcquisitionSource = UnitAcquisitionSource;
export type ProductAccessoryLink = ProductAccessory;
export type TokenResponse = CustomerLogin;
export type AdminProfileResponse = Admin;

// User type with optional username for compatibility  
// Note: User is already exported above on line 136, and imported as type on line 192
export type UserCompat = Omit<User, 'username'> & { username?: string };

// Custom types and constants (not generated by openapi-typescript-codegen)
// These are defined here to avoid being overwritten when regenerating API clients
export type StockAlert = {
  id?: number;
  type?: string;
  severity?: string;
  title?: string;
  message?: string;
  product_id?: number;
  product_name?: string;
  current_stock?: number;
  min_threshold?: number;
  action?: string;
  link?: string;
  unit_id?: number;
  expires_at?: string;
  reserved_by?: string;
  hours_remaining?: number;
  count?: number;
};

export type StockAlertsResponse = {
  alerts: Array<StockAlert>;
  count?: number;
};

// Alert type constants
// DEBUG_MARKER: INVENTORY_MANAGEMENT_FRONTEND_SRC_API_INDEX_TS
export const StockAlertType = {
  OUT_OF_STOCK: 'out_of_stock',
  LOW_STOCK: 'low_stock',
  EXPIRING_RESERVATION: 'expiring_reservation',
  PENDING_APPROVAL: 'pending_approval',
} as const;

